version: "3.9"

services:
  db:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      #a bind mount 
      - type: bind
        source: ./db_data
        target: /var/lib/mysql
      - type: bind
        source: ./db_conf
        target: /etc/mysql/conf.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mybatis
      MYSQL_USER: mybatis
      MYSQL_PASSWORD: mybatis
    ports:
      - "33060:3306"